language: node_js
dist: trusty
node_js:
  - 9
  - 8
  - 7
notifications:
  email:
    on_failure: change
script:
  - node --version
  - yarn --version
  - yarn run lint
  - yarn run test:noWatch
  - echo 'List ----------------------------------------------------------------'
  - ls -a ./
  - echo 'Git ls --------------------------------------------------------------'
  - git ls-files
  - codecov
  - yarn run build
cache:
  yarn: true
  directories:
    - node_modules