language: node_js
dist: trusty
node_js:
  - 7
  - 8
notifications:
  email:
    on_failure: change
script:
  - node --version
  - yarn --version
  - yarn run verify
  - codecov
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules